### ISSUE TITLE
"EMBED" and "DEMO_EMBED" mis-compatibilites 

### ISSUE THREAD

**Issue by hexonMD** [saasquatch/dollar-credit-theme#2]
![noname](https://cloud.githubusercontent.com/assets/3913256/6693618/802f8d9c-cc91-11e4-8214-43009b8defef.gif)

Differences can be noted in gif above.

Issue is present in all three widget types.

**Comment by karlhorky** [comment]
This can be resolved by using the `squatch-container-popup` class instead of the `squatch-container-embed` class to do the popup styling. For instance here: https://github.com/saasquatch/dollar-credit-theme/blob/ab52a5ab01299bdc3a8a734e6d553482c84cfef2/assets/css/_theme.less#L84-L86
